// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExtendedSortableController from "./extended_sortable_controller"
application.register("extended-sortable", ExtendedSortableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TextareaAutosizeController from "./textarea_autosize_controller"
application.register("textarea-autosize", TextareaAutosizeController)
